/**
 * Socket.IO Event Codes
 * Consistent event names for client-server communication
 * Based on the original shelf-3.2.4-og socket codes
 */

// Records - Collection
export const INITIAL_RECORD_COLLECTION_IN_PROGRESS = 'INITIAL_RECORD_COLLECTION_IN_PROGRESS';
export const RECORD_COLLECTION = 'RECORD_COLLECTION';
export const ADDED_RECORD_TO_COLLECTION = 'ADDED_RECORD_TO_COLLECTION';
export const UPDATED_RECORD_IN_COLLECTION = 'UPDATED_RECORD_IN_COLLECTION';
export const REMOVED_RECORD_FROM_COLLECTION = 'REMOVED_RECORD_FROM_COLLECTION';

// Records - Wishlist
export const RECORD_WISHLIST = 'RECORD_WISHLIST';
export const ADDED_RECORD_TO_WISHLIST = 'ADDED_RECORD_TO_WISHLIST';
export const UPDATED_RECORD_IN_WISHLIST = 'UPDATED_RECORD_IN_WISHLIST';
export const REMOVED_RECORD_FROM_WISHLIST = 'REMOVED_RECORD_FROM_WISHLIST';

// Board Games - Collection
export const INITIAL_BOARD_GAME_COLLECTION_IN_PROGRESS = 'INITIAL_BOARD_GAME_COLLECTION_IN_PROGRESS';
export const BOARD_GAME_COLLECTION = 'BOARD_GAME_COLLECTION';
export const ADDED_BOARD_GAME_TO_COLLECTION = 'ADDED_BOARD_GAME_TO_COLLECTION';
export const UPDATED_BOARD_GAME_IN_COLLECTION = 'UPDATED_BOARD_GAME_IN_COLLECTION';
export const REMOVED_BOARD_GAME_FROM_COLLECTION = 'REMOVED_BOARD_GAME_FROM_COLLECTION';

// Board Games - Wishlist
export const BOARD_GAME_WISHLIST = 'BOARD_GAME_WISHLIST';
export const ADDED_BOARD_GAME_TO_WISHLIST = 'ADDED_BOARD_GAME_TO_WISHLIST';
export const UPDATED_BOARD_GAME_IN_WISHLIST = 'UPDATED_BOARD_GAME_IN_WISHLIST';
export const REMOVED_BOARD_GAME_FROM_WISHLIST = 'REMOVED_BOARD_GAME_FROM_WISHLIST';

// Books - Collection
export const INITIAL_BOOK_COLLECTION_IN_PROGRESS = 'INITIAL_BOOK_COLLECTION_IN_PROGRESS';
export const BOOK_COLLECTION = 'BOOK_COLLECTION';
export const ADDED_BOOK_TO_COLLECTION = 'ADDED_BOOK_TO_COLLECTION';
export const UPDATED_BOOK_IN_COLLECTION = 'UPDATED_BOOK_IN_COLLECTION';
export const REMOVED_BOOK_FROM_COLLECTION = 'REMOVED_BOOK_FROM_COLLECTION';

// Books - Wishlist
export const BOOK_WISHLIST = 'BOOK_WISHLIST';
export const ADDED_BOOK_TO_WISHLIST = 'ADDED_BOOK_TO_WISHLIST';
export const UPDATED_BOOK_IN_WISHLIST = 'UPDATED_BOOK_IN_WISHLIST';
export const REMOVED_BOOK_FROM_WISHLIST = 'REMOVED_BOOK_FROM_WISHLIST';

// Sync Status Events
export const SYNC_PROGRESS = 'SYNC_PROGRESS';
export const SYNC_COMPLETE = 'SYNC_COMPLETE';
export const SYNC_ERROR = 'SYNC_ERROR';